import { ServiceDetails, Scheme } from './types';

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    hero_title: "Government services, finally simple.",
    hero_subtitle: "Access official guidelines, verify document portfolios, explore social welfare schemes, and navigate state procedures in simple language without middlemen.",
    search_placeholder: "Try searching 'Aadhaar correction', 'Driving license', 'Ayushman health card'...",
    search_btn: "Search",
    nav_services: "Services",
    nav_documents: "Document Checker",
    nav_schemes: "Scheme Finder",
    nav_track: "Track Applications",
    nav_my_apps: "My Sewa Center",
    stats_services: "12+ Live Services",
    stats_languages: "8+ Indian Languages",
    stats_middlemen: "0% Middlemen Fees",
    stats_free: "Verify Free",
    stats_label_1: "Central & State services detailed",
    stats_label_2: "Read, translate & query in your voice",
    stats_label_3: "Direct official URLs & strict guidelines",
    stats_label_4: "Instant validation rules checklist",
    section_categories: "Explore by Sector",
    section_popular: "Popular Citizen Services",
    section_how_it_works: "How Government is Simplified",
    step1_title: "1. Search Instantly",
    step1_desc: "Query any central or state civic services with smart multilingual auto-suggest.",
    step2_title: "2. Verify Portfolio",
    step2_desc: "Generate active checklists of legal papers accepted for application validation.",
    step3_title: "3. Align Demographics",
    step3_desc: "Evaluate matching thresholds for state welfare subsidies customized to your profile.",
    step4_title: "4. Apply Securely",
    step4_desc: "Redirect directly to authorized government department portals with zero commission.",
    chat_placeholder: "Type your civic question to SevAI...",
    chat_welcome: "Namaste! I am SevAI, your digital e-Governance advisor. I help citizens verify required certificates, matching social schemes, and step-by-step procedures in absolute simple terms. Ask me anything!",
    footer_tagline: "SarkarSeva — Empowering Indian Citizens with Transparent Digital Governance.",
    footer_disclaimer: "Disclaimer: This digital portal serves strictly as an educational simplified knowledge aggregator. We are not a government agency. All links redirect securely to verified official portals (uidai.gov.in, parivahan.gov.in, etc.) in compliance with open standards.",
    btn_apply: "Go to Official Portal",
    btn_download: "Download Checklist PDF",
    btn_track: "Check Live Status",
    btn_share: "Share Guide",
    badge_popular: "Popular",
    badge_new: "New",
    badge_scheme: "Subsidy",
    badge_free: "Free",
    badge_online: "Online",
    badge_offline: "At Center"
  },
  hi: {
    hero_title: "सरकारी सेवाएं, आखिरकार आसान।",
    hero_subtitle: "आधिकारिक दिशानिर्देशों तक पहुंचें, आवश्यक दस्तावेजों का सत्यापन करें, सामाजिक कल्याण योजनाओं का पता लगाएं और बिना किसी बिचौलियों के सरल भाषा में सरकारी प्रक्रियाओं को समझें।",
    search_placeholder: "खोजें 'आधार सुधार', 'ड्राइविंग लाइसेंस', 'आयुष्मान कार्ड'...",
    search_btn: "खोजें",
    nav_services: "सेवाएं",
    nav_documents: "दस्तावेज़ चेकर",
    nav_schemes: "योजना खोजक",
    nav_track: "आवेदन ट्रैक करें",
    nav_my_apps: "मेरा सेवा केंद्र",
    stats_services: "12+ लाइव सेवाएं",
    stats_languages: "8+ भारतीय भाषाएं",
    stats_middlemen: "0% बिचौलिया शुल्क",
    stats_free: "मुफ्त सत्यापन",
    stats_label_1: "विस्तृत केंद्रीय और राज्य सेवाएं",
    stats_label_2: "पढ़ें, अनुवाद करें और अपनी आवाज में पूछें",
    stats_label_3: "सीधे आधिकारिक लिंक और दिशानिर्देश",
    stats_label_4: "त्वरित मान्यता नियम चेकलिस्ट",
    section_categories: "श्रेणियों के अनुसार खोजें",
    section_popular: "लोकप्रिय नागरिक सेवाएं",
    section_how_it_works: "सरकारी प्रक्रियाएं कैसे आसान होती हैं",
    step1_title: "1. तुरंत खोजें",
    step1_desc: "बहुभाषी ऑटो-सुझाव के साथ किसी भी केंद्रीय या राज्य नागरिक सेवाओं को खोजें।",
    step2_title: "2. दस्तावेज़ जांचें",
    step2_desc: "आवेदन सत्यापन के लिए स्वीकार किए गए आवश्यक दस्तावेजों की सक्रिय सूची बनाएं।",
    step3_title: "3. प्रोफाइल मिलाएं",
    step3_desc: "अपनी प्रोफाइल के अनुसार कल्याणकारी योजनाओं और रियायतों की पात्रता जांचें।",
    step4_title: "4. सुरक्षित आवेदन",
    step4_desc: "शून्य कमीशन के साथ सीधे अधिकृत सरकारी विभाग पोर्टलों पर जाएं।",
    chat_placeholder: "SevAI से अपना नागरिक प्रश्न पूछें...",
    chat_welcome: "नमस्ते! मैं SevAI हूं, आपका डिजिटल ई-गवर्नेंस सलाहकार। मैं नागरिकों को आवश्यक दस्तावेजों, सामाजिक योजनाओं और चरण-दर-चरण प्रक्रियाओं को सरल शब्दों में सत्यापित करने में मदद करता हूं। कुछ भी पूछें!",
    footer_tagline: "SarkarSeva — पारदर्शी डिजिटल शासन के साथ भारतीय नागरिकों को सशक्त बनाना।",
    footer_disclaimer: "अस्वीकरण: यह डिजिटल पोर्टल केवल एक सरल शैक्षणिक ज्ञान प्रदाता के रूप में कार्य करता है। हम सरकारी एजेंसी नहीं हैं। सभी लिंक सत्यापित आधिकारिक पोर्टलों पर रीडायरेक्ट होते हैं।",
    btn_apply: "आधिकारिक पोर्टल पर जाएं",
    btn_download: "चेकलिस्ट डाउनलोड करें",
    btn_track: "लाइव स्टेटस जांचें",
    btn_share: "गाइड साझा करें",
    badge_popular: "लोकप्रिय",
    badge_new: "नया",
    badge_scheme: "योजना",
    badge_free: "निःशुल्क",
    badge_online: "ऑनलाइन",
    badge_offline: "केंद्र पर"
  },
  mr: {
    hero_title: "सरकारी सेवा, शेवटी सोपी।",
    hero_subtitle: "अधिकृत मार्गदर्शक तत्त्वे मिळवा, आवश्यक कागदपत्रांचे पुनरावलोकन करा, समाजकल्याण योजना शोधा आणि मध्यस्थांशिवाय सोप्या भाषेत प्रक्रियेचे नेतृत्व करा.",
    search_placeholder: "शोधा 'आधार दुरुस्ती', 'ड्रायव्हिंग लायसन्स', 'आयुष्मान आरोग्य कार्ड'...",
    search_btn: "शोधा",
    nav_services: "सेवा",
    nav_documents: "कागदपत्र तपासक",
    nav_schemes: "योजना शोधक",
    nav_track: "अर्जाचा मागोवा",
    nav_my_apps: "माझे सेवा केंद्र",
    stats_services: "12+ सक्रिय सेवा",
    stats_languages: "8+ भारतीय भाषा",
    stats_middlemen: "0% मध्यस्थ शुल्क",
    stats_free: "मोफत पडताळणी",
    stats_label_1: "तपशीलवार केंद्रीय आणि राज्य सेवा",
    stats_label_2: "तुमच्या भाषेत वाचा आणि प्रश्न विचारा",
    stats_label_3: "थेट अधिकृत लिंक्स आणि मार्गदर्शक तत्त्वे",
    stats_label_4: "त्वरित पडताळणी नियमांची चेकलिस्ट",
    section_categories: "क्षेत्रानुसार शोधा",
    section_popular: "लोकप्रिय नागरिक सेवा",
    section_how_it_works: "सरकारी प्रक्रिया सोपी कशी होते",
    step1_title: "1. त्वरित शोधा",
    step1_desc: "स्मार्ट बहुभाषिक ऑटो-सुझावांसह कोणत्याही केंद्रीय किंवा राज्य सेवा शोधा.",
    step2_title: "2. कागदपत्रे तपासा",
    step2_desc: "अर्ज मंजुरीसाठी आवश्यक असलेल्या कागदपत्रांची सक्रिय चेकलिस्ट तयार करा.",
    step3_title: "3. पात्रता तपासा",
    step3_desc: "तुमच्या प्रोफाइलनुसार जुळणाऱ्या राज्य कल्याणकारी योजना आणि अनुदानांचे मूल्यांकन करा.",
    step4_title: "4. सुरक्षित अर्ज",
    step4_desc: "थेट अधिकृत सरकारी विभाग पोर्टलवर शून्य कमिशनसह पुनर्निर्देशित व्हा.",
    chat_placeholder: "SevAI ला प्रश्न विचारा...",
    chat_welcome: "नमस्कार! मी SevAI आहे, तुमचा डिजिटल ई-गव्हर्नन्स मार्गदर्शक. मी नागरिकांना आवश्यक कागदपत्रे, कल्याणकारी योजना आणि सरकारी प्रक्रिया अत्यंत सोप्या शब्दांत पडताळण्यास मदत करतो. काहीही विचारा!",
    footer_tagline: "SarkarSeva — पारदर्शक डिजिटल प्रशासनाद्वारे भारतीय नागरिकांना सक्षम करणे.",
    footer_disclaimer: "Disclaimer: हे डिजिटल पोर्टल केवळ शैक्षणिक सुलभ ज्ञान एकत्रित करणारे साधन म्हणून काम करते. आम्ही सरकारी संस्था नाही. सर्व लिंक्स सुरक्षितपणे अधिकृत पोर्टल्सवर पाठवतात.",
    btn_apply: "आधिकारिक पोर्टलवर जा",
    btn_download: "चेकलिस्ट डाउनलोड करा",
    btn_track: "लाइव स्टेटस पहा",
    btn_share: "माहिती शेअर करा",
    badge_popular: "लोकप्रिय",
    badge_new: "नवीन",
    badge_scheme: "योजना",
    badge_free: "मोफत",
    badge_online: "ऑनलाइन",
    badge_offline: "केंद्रावर"
  },
  ta: {
    hero_title: "அரசு சேவைகள், இறுதியாக எளிமையானது.",
    hero_subtitle: "அதிகாரப்பூர்வ வழிகாட்டுதல்களை அணுகவும், தேவையான ஆவணங்களைச் சரிபார்க்கவும், சமூக நலத் திட்டங்களை ஆராயவும் மற்றும் தரகர்கள் இல்லாத எளிய மொழியில் அரசு நடைமுறைகளை அறிந்து கொள்ளவும்.",
    search_placeholder: "தேடுக 'ஆதார் திருத்தம்', 'ஓட்டுநர் உரிமம்', 'ஆயுஷ்மான் அட்டை'...",
    search_btn: "தேடு",
    nav_services: "சேவைகள்",
    nav_documents: "ஆவண சரிபார்ப்பு",
    nav_schemes: "திட்டங்கள் கண்டறிவி",
    nav_track: "நிலையை கண்காணி",
    nav_my_apps: "எனது சேவை மையம்",
    stats_services: "12+ நேரடி சேவைகள்",
    stats_languages: "8+ இந்திய மொழிகள்",
    stats_middlemen: "0% தரகர் கட்டணம்",
    stats_free: "இலவச சரிபார்ப்பு",
    stats_label_1: "மத்திய மற்றும் மாநில சேவைகள் விரிவாக",
    stats_label_2: "படிக்க, மொழிபெயர்க்க மற்றும் உங்கள் குரலில் கேட்க",
    stats_label_3: "நேரடி அதிகாரப்பூர்வ இணைப்புகள் மற்றும் வழிகாட்டுதல்கள்",
    stats_label_4: "உடனடி சரிபார்ப்பு விதிகள் சரிபார்ப்பு பட்டியல்",
    section_categories: "துறை வாரியாக ஆராயுங்கள்",
    section_popular: "பிரபலமான குடிமக்கள் சேவைகள்",
    section_how_it_works: "அரசு நடைமுறைகள் எவ்வாறு எளிமையாக்கப்படுகின்றன",
    step1_title: "1. உடனடியாக தேடுங்கள்",
    step1_desc: "ஸ்மார்ட் பன்மொழி பரிந்துரைகளுடன் எந்தவொரு மத்திய அல்லது மாநில சேவைகளையும் தேடுங்கள்.",
    step2_title: "2. ஆவணங்களைச் சரிபார்க்கவும்",
    step2_desc: "விண்ணப்ப ஒப்புதலுக்குத் தேவையான ஆவணங்களின் செயலில் உள்ள பட்டியலை உருவாக்கவும்.",
    step3_title: "3. தகுதியை சரிபார்க்க",
    step3_desc: "உங்கள் சுயவிவரத்திற்கு ஏற்ற அரசு நலத்திட்டங்கள் மற்றும் மானியங்களை மதிப்பீடு செய்யவும்.",
    step4_title: "4. பாதுகாப்பாக விண்ணப்பிக்க",
    step4_desc: "பூஜ்ஜிய கமிஷனுடன் நேரடியாக அங்கீகரிக்கப்பட்ட அரசுத் துறை போர்ட்டல்களுக்குச் செல்லவும்.",
    chat_placeholder: "SevAI-இடம் உங்கள் குடிமை கேள்வியைக் கேளுங்கள்...",
    chat_welcome: "வணக்கம்! நான் SevAI, உங்கள் டிஜிட்டல் மின்-ஆளுமை ஆலோசகர். குடிமக்கள் தேவைப்படும் ஆவணங்கள், சமூக நலத்திட்டங்கள் மற்றும் அரசு நடைமுறைகளை எளிய முறையில் சரிபார்க்க உதவுகிறேன். ஏதேனும் கேளுங்கள்!",
    footer_tagline: "SarkarSeva — வெளிப்படையான டிஜிட்டல் நிர்வாகத்தின் மூலம் இந்திய குடிமக்களை மேம்படுத்துதல்.",
    footer_disclaimer: "பொறுப்புத் துறப்பு: இந்த டிஜிட்டல் போர்டல் எளிமைப்படுத்தப்பட்ட கல்வித் தகவல் தளம் மட்டுமே. நாங்கள் அரசு நிறுவனம் அல்ல. அனைத்து இணைப்புகளும் அதிகாரப்பூர்வ போர்ட்டல்களுக்கு பாதுகாப்பாக அனுப்பப்படுகின்றன.",
    btn_apply: "அதிகாரப்பூர்வ தளத்திற்குச் செல்லவும்",
    btn_download: "பட்டியலை பதிவிறக்கவும்",
    btn_track: "நேரடி நிலையை சரிபார்க்கவும்",
    btn_share: "வழிகாட்டியைப் பகிரவும்",
    badge_popular: "பிரபலம்",
    badge_new: "புதியது",
    badge_scheme: "நிவாரணம்",
    badge_free: "இலவசம்",
    badge_online: "ஆன்லைன்",
    badge_offline: "மையத்தில்"
  },
  te: {
    hero_title: "ప్రభుత్వ సేవలు, చివరకు సులభం.",
    hero_subtitle: "అధికారిక మార్గదర్శకాలను యాక్సెస్ చేయండి, కావలసిన పత్రాలను ధృవీకరించుకోండి, సంక్షేమ పథకాలను కనుగొనండి మరియు దళారులు లేకుండా సరళమైన భాషలో ప్రక్రియలను అర్థం చేసుకోండి.",
    search_placeholder: "వెతకండి 'ఆధార్ సవరణ', 'డ్రైవింగ్ లైసెన్స్', 'ఆయుష్మాన్ కార్డ్'...",
    search_btn: "వెతకండి",
    nav_services: "సేవలు",
    nav_documents: "పత్రాల వెరిఫైయర్",
    nav_schemes: "పథకాల అన్వేషణ",
    nav_track: "అప్లికేషన్ ట్రాకింగ్",
    nav_my_apps: "నా సేవా కేంద్రం",
    stats_services: "12+ ప్రత్యక్ష సేవలు",
    stats_languages: "8+ భారతీయ భాషలు",
    stats_middlemen: "0% దళారీ రుసుము",
    stats_free: "ఉచిత ధృవీకరణ",
    stats_label_1: "వివరణాత్మక కేంద్ర మరియు రాష్ట్ర సేవలు",
    stats_label_2: "మీ స్వంత భాషలోనే చదవండి మరియు అడగండి",
    stats_label_3: "నేరుగా అధికారిక లింకులు మరియు గైడ్‌లు",
    stats_label_4: "తక్షణ ధృవీకరణ నిబంధనల చెక్లిస్ట్",
    section_categories: "విభాగాల వారీగా అన్వేషించండి",
    section_popular: "ప్రజాదరణ పొందిన పౌర సేవలు",
    section_how_it_works: "ప్రభుత్వ సేవలు ఎలా సులభతరం అవుతాయి",
    step1_title: "1. తక్షణమే శోధించండి",
    step1_desc: "స్మార్ట్ బహుభాషా ఆటో-సూచనలతో ఏదైనా కేంద్ర లేదా రాష్ట్ర సేవలను శోధించండి.",
    step2_title: "2. పత్రాలను ధృవీకరించండి",
    step2_desc: "అప్లికేషన్ ఆమోదానికి అవసరమైన పత్రాల క్రియాశీల సంకలనాన్ని సృష్టించండి.",
    step3_title: "3. అర్హతలను సరిపోల్చండి",
    step3_desc: "మీ ప్రొఫైల్ ఆధారంగా సరిపోయే సంక్షేమ పథకాలు మరియు రాయితీలను అంచనా వేయండి.",
    step4_title: "4. సురక్షితంగా దరఖాస్తు",
    step4_desc: "ఎలాంటి కమిషన్ లేకుండా నేరుగా అధికారిక ప్రభుత్వ శాఖ పోర్టల్‌లకు వెళ్ళండి.",
    chat_placeholder: "SevAIని మీ పౌర ప్రశ్న అడగండి...",
    chat_welcome: "నమస్తే! నేను SevAI, మీ డిజిటల్ ఈ-గవర్నెన్స్ గైడ్. పౌరులకు అవసరమైన పత్రాలు, సంక్షేమ పథకాలు మరియు ప్రభుత్వ ప్రక్రియలను సులభమైన పదాలలో వెరిఫై చేయడంలో సహాయపడతాను. ఏదైనా అడగండి!",
    footer_tagline: "SarkarSeva — పారదర్శక డిజిటల్ పాలనతో భారతీయ పౌరులను బలోపేతం చేయడం.",
    footer_disclaimer: "గమనిక: ఈ డిజిటల్ పోర్టల్ కేవలం విద్యాపరమైన సమాచార వేదిక మాత్రమే. మేము ప్రభుత్వ సంస్థ కాదు. అన్ని లింకులు సురక్షితంగా అధికారిక పోర్టల్‌లకు మళ్లించబడతాయి.",
    btn_apply: "అధికారిక పోర్టల్‌కు వెళ్ళండి",
    btn_download: "చెక్లిస్ట్ డౌన్‌లోడ్ చేసుకోండి",
    btn_track: "లైవ్ అప్లికేషన్ స్టేటస్",
    btn_share: "గైడ్‌ను షేర్ చేయండి",
    badge_popular: "పాపులర్",
    badge_new: "కొత్తది",
    badge_scheme: "పథకం",
    badge_free: "ఉచితం",
    badge_online: "ఆన్‌లైన్",
    badge_offline: "కేంద్రంలో"
  },
  bn: {
    hero_title: "সরকারি পরিষেবা, অবশেষে সহজ।",
    hero_subtitle: "কোনো দালাল ছাড়াই সহজ বাংলায় সরকারি নির্দেশিকা অ্যাক্সেস করুন, প্রয়োজনীয় নথি পরীক্ষা করুন, সমাজকল্যাণ প্রকল্পগুলি সন্ধান করুন এবং আবেদন প্রক্রিয়াগুলি বুঝুন।",
    search_placeholder: "খুঁজুন 'আধার সংশোধন', 'ড্রাইভিং লাইসেন্স', 'আয়ুষ্মান স্বাস্থ্য কার্ড'...",
    search_btn: "খুঁজুন",
    nav_services: "পরিষেবাসমূহ",
    nav_documents: "নথি পরীক্ষক",
    nav_schemes: "প্রকল্প সন্ধানকারী",
    nav_track: "আবেদন ট্র্যাকিং",
    nav_my_apps: "আমার সেবা কেন্দ্র",
    stats_services: "১২+ লাইভ পরিষেবা",
    stats_languages: "৮+ ভারতীয় ভাষা",
    stats_middlemen: "০% দালাল ফি",
    stats_free: "বিনামূল্যে যাচাই",
    stats_label_1: "বিস্তারিত কেন্দ্রীয় ও রাজ্য পরিষেবা",
    stats_label_2: "পড়ুন, অনুবাদ করুন এবং আপনার নিজের ভাষায় জিজ্ঞাসা করুন",
    stats_label_3: "সরাসরি অফিসিয়াল লিংক এবং নির্দেশিকা",
    stats_label_4: "তাত্ক্ষণিক যাচাইকরণ নিয়মের চেকলিস্ট",
    section_categories: "বিভাগ অনুসারে অন্বেষণ করুন",
    section_popular: "জনপ্রিয় নাগরিক পরিষেবাসমূহ",
    section_how_it_works: "সরকারি প্রক্রিয়া যেভাবে সহজ করা হয়েছে",
    step1_title: "১. তাত্ক্ষণিকভাবে অনুসন্ধান",
    step1_desc: "বহুভাষী অটো-সাজেশনের সাথে যেকোনো কেন্দ্রীয় বা রাজ্য নাগরিক পরিষেবা খোঁজেন।",
    step2_title: "২. নথি যাচাই করুন",
    step2_desc: "আবেদন অনুমোদনের জন্য প্রয়োজনীয় আইনি নথিপত্রের সক্রিয় চেকলিস্ট তৈরি করুন।",
    step3_title: "৩. যোগ্যতা যাচাই করুন",
    step3_desc: "আপনার প্রোফাইলের সাথে সামঞ্জस्यপূর্ণ সরকারি অনুদান এবং সামাজিক প্রকল্পগুলি মূল্যায়ন করুন।",
    step4_title: "৪. নিরাপদে আবেদন করুন",
    step4_desc: "কোনো কমিশন ছাড়াই সরাসরি অনুমোদিত সরকারি বিভাগের পোর্টালে যান।",
    chat_placeholder: "SevAI-কে আপনার নাগরিক প্রশ্ন জিজ্ঞাসা করুন...",
    chat_welcome: "নমস্কার! আমি SevAI, আপনার ডিজিটাল ই-গভর্নেন্স গাইড। আমি নাগরিকদের প্রয়োজনীয় বন্ধনীসমূহ, সরকারি প্রকল্প এবং আবেদন প্রক্রিয়া সহজ বাংলায় যাচাই করতে সাহায্য করি। যেকোনো কিছু জিজ্ঞাসা করুন!",
    footer_tagline: "SarkarSeva — স্বচ্ছ ডিজিটাল প্রশাসনের মাধ্যমে ভারতীয় নাগরিকদের ক্ষমতায়ন করা।",
    footer_disclaimer: "দাবিত্যাগ: এই ডিজিটাল পোর্টালটি কেবল একটি সরলীকৃত শিক্ষামূলক তথ্য সরবরাহকারী। আমরা কোনো সরকারি সংস্থা নই। সমস্ত সংযোগগুলি নিরাপদভাবে অফিসিয়াল পোর্টালে পুনঃনির্দেশিত করা হয়।",
    btn_apply: "অফিসিয়াল পোর্টালে যান",
    btn_download: "চেকলিস্ট ডাউনলোড করুন",
    btn_track: "লাইভ স্ট্যাটাস চেক করুন",
    btn_share: "গাইড শেয়ার করুন",
    badge_popular: "জনপ্রিয়",
    badge_new: "নতুন",
    badge_scheme: "ভর্তুকি",
    badge_free: "বিনামূল্যে",
    badge_online: "অনলাইন",
    badge_offline: "কেন্দ্রে"
  },
  pa: {
    hero_title: "ਸਰਕਾਰੀ ਸੇਵਾਵਾਂ, ਅੰਤ ਵਿੱਚ ਸਰਲ।",
    hero_subtitle: "ਅਧਿਕਾਰਤ ਦਿਸ਼ਾ-ਨਿਰਦੇਸ਼ਾਂ ਤੱਕ ਪਹੁੰਚੋ, ਜ਼ਰੂਰੀ ਦਸਤਾਵੇਜ਼ਾਂ ਦੀ ਜਾਂਚ ਕਰੋ, ਸਮਾਜ ਭਲਾਈ ਸਕੀਮਾਂ ਬਾਰੇ ਜਾਣੋ ਅਤੇ ਬਿਨਾਂ ਕਿਸੇ ਵਿਚੋਲੇ ਦੇ ਸਧਾਰਨ ਭਾਸ਼ਾ ਵਿੱਚ ਸਰਕਾਰੀ ਪ੍ਰਕਿਰਿਆਵਾਂ ਨੂੰ ਸਮਝੋ।",
    search_placeholder: "ਖੋਜੋ 'ਆਧਾਰ ਸੁਧਾਰ', 'ਡਰਾਈਵਿੰਗ ਲਾਇਸੰਸ', 'ਆਯੁਸ਼ਮਾਨ ਸਿਹਤ ਕਾਰਡ'...",
    search_btn: "ਖੋਜੋ",
    nav_services: "ਸੇਵਾਵਾਂ",
    nav_documents: "ਦਸਤਾਵੇਜ਼ ਚੈਕਰ",
    nav_schemes: "ਸਕੀਮ ਖੋਜੀ",
    nav_track: "ਅਰਜ਼ੀ ਟ੍ਰੈਕ ਕਰੋ",
    nav_my_apps: "ਮੇਰਾ ਸੇਵਾ ਕੇਂਦਰ",
    stats_services: "12+ ਲਾਈਵ ਸੇਵਾਵਾਂ",
    stats_languages: "8+ ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ",
    stats_middlemen: "0% ਵਿਚੋਲਾ ਫੀਸ",
    stats_free: "ਮੁਫ਼ਤ ਵੈਰੀਫਿਕੇਸ਼ਨ",
    stats_label_1: "ਵਿਸਤ੍ਰਿਤ ਕੇਂਦਰੀ ਅਤੇ ਰਾਜ ਸੇਵਾਵਾਂ",
    stats_label_2: "ਪੜ੍ਹੋ, ਅਨੁਵਾਦ ਕਰੋ ਅਤੇ ਆਪਣੀ ਆਵਾਜ਼ ਵਿੱਚ ਪੁੱਛੋ",
    stats_label_3: "ਸਿੱਧੇ ਅਧਿਕਾਰਤ ਲਿੰਕ ਅਤੇ ਦਿਸ਼ਾ-ਨਿਰਦੇਸ਼",
    stats_label_4: "ਤੁਰੰਤ ਪ੍ਰਵਾਨਗੀ ਨਿਯਮਾਂ ਦੀ ਚੈੱਕਲਿਸਟ",
    section_categories: "ਸ਼੍ਰੇਣੀਆਂ ਦੇ ਅਨੁਸਾਰ ਖੋਜੋ",
    section_popular: "ਪ੍ਰਸਿੱਧ ਨਾਗਰਿਕ ਸੇਵਾਵਾਂ",
    section_how_it_works: "ਸਰਕਾਰੀ ਪ੍ਰਕਿਰਿਆਵਾਂ ਨੂੰ ਕਿਸ ਤਰ੍ਹਾਂ ਸਰਲ ਬਣਾਇਆ ਗਿਆ ਹੈ",
    step1_title: "1. ਤੁਰੰਤ ਖੋਜੋ",
    step1_desc: "ਸਮਾਰਟ ਬਹੁ-ਭਾਸ਼ਾਈ ਸੁਝਾਵਾਂ ਨਾਲ ਕਿਸੇ ਵੀ ਕੇਂਦਰੀ ਜਾਂ ਰਾਜ ਸੇਵਾਵਾਂ ਨੂੰ ਲੱਭੋ।",
    step2_title: "2. ਦਸਤਾਵੇਜ਼ਾਂ ਦੀ ਜਾਂਚ ਕਰੋ",
    step2_desc: "ਅਰਜ਼ੀ ਦੀ ਪ੍ਰਵਾਨਗੀ ਲਈ ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼ਾਂ ਦੀ ਸਰਗਰਮ ਚੈੱਕਲਿਸਟ ਤਿਆਰ ਕਰੋ।",
    step3_title: "3. ਯੋਗਤਾ ਦੀ ਜਾਂਚ ਕਰੋ",
    step3_desc: "ਆਪਣੇ ਪ੍ਰੋਫਾਈਲ ਅਨੁਸਾਰ ਮੇਲ ਖਾਂਦੀਆਂ ਭਲਾਈ ਸਕੀਮਾਂ ਅਤੇ ਸਬਸਿਡੀਆਂ ਦਾ ਮੁਲਾਂਕਣ ਕਰੋ।",
    step4_title: "4. ਸੁਰੱਖਿਅਤ ਅਪਲਾਈ",
    step4_desc: "ਬਿਨਾਂ ਕਿਸੇ ਕਮਿਸ਼ਨ ਦੇ ਸਿੱਧੇ ਅਧਿਕਾਰਤ ਸਰਕਾਰੀ ਵਿਭਾਗ ਦੇ ਪੋਰਟਲ 'ਤੇ ਜਾਓ।",
    chat_placeholder: "SevAI ਨੂੰ ਆਪਣਾ ਨਾਗਰਿਕ ਸਵਾਲ ਪੁੱਛੋ...",
    chat_welcome: "ਨਮਸਤੇ! ਮੈਂ SevAI ਹਾਂ, ਤੁਹਾਡਾ ਡਿਜੀਟਲ ਈ-ਗਵਰਨੈਂਸ ਸਲਾਹਕਾਰ। ਮੈਂ ਨਾਗਰਿਕਾਂ ਨੂੰ ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼ਾਂ, ਸਮਾਜਿਕ ਸਕੀਮਾਂ ਅਤੇ ਕਦਮ-ਦਰ-ਕਦਮ ਸਰਕਾਰੀ ਪ੍ਰਕਿਰਿਆਵਾਂ ਨੂੰ ਸਰਲ ਭਾਸ਼ਾ ਵਿੱਚ ਸਮਝਾਉਣ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹਾਂ। ਕੁਝ ਵੀ ਪੁੱਛੋ!",
    footer_tagline: "SarkarSeva — ਪਾਰਦਰਸ਼ੀ ਡਿਜੀਟਲ ਪ੍ਰਸ਼ਾਸਨ ਰਾਹੀਂ ਭਾਰਤੀ ਨਾਗਰਿਕਾਂ ਨੂੰ ਸਮਰੱਥ ਬਣਾਉਣਾ।",
    footer_disclaimer: "Disclaimer: ਇਹ ਡਿਜੀਟਲ ਪੋਰਟਲ ਸਿਰਫ ਸੁਵਿਧਾਜਨਕ ਵਿਦਿਅਕ ਜਾਣਕਾਰੀ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ। ਅਸੀਂ ਕੋਈ ਸਰਕਾਰੀ ਏਜੰਸੀ ਨਹੀਂ ਹਾਂ। ਸਾਰੇ ਲਿੰਕ ਸੁਰੱਖਿਅਤ ਰੂਪ ਨਾਲ ਅਧਿਕਾਰਤ ਪੋਰਟਲ 'ਤੇ ਲੈ ਜਾਂਦੇ ਹਨ।",
    btn_apply: "ਅਧਿਕਾਰਤ ਪੋਰਟਲ 'ਤੇ ਜਾਓ",
    btn_download: "ਚੈੱਕਲਿਸਟ ਡਾਊਨਲੋਡ ਕਰੋ",
    btn_track: "ਲਾਈਵ ਸਟੇਟਸ ਦੇਖੋ",
    btn_share: "ਗਾਈਡ ਸਾਂਝਾ ਕਰੋ",
    badge_popular: "ਪ੍ਰਸਿੱਧ",
    badge_new: "ਨਵਾਂ",
    badge_scheme: "ਯੋਜਨਾ",
    badge_free: "ਮੁਫ਼ਤ",
    badge_online: "ਔਨਲਾਈਨ",
    badge_offline: "ਕੇਂਦਰ 'ਤੇ"
  },
  kn: {
    hero_title: "ಸರ್ಕಾರಿ ಸೇವೆಗಳು, ಕೊನೆಗೂ ಸರಳ.",
    hero_subtitle: "ಅಧಿಕೃತ ಮಾರ್ಗಸೂಚಿಗಳನ್ನು ವೀಕ್ಷಿಸಿ, ಅಗತ್ಯವಿರುವ ದಸ್ತಾವೇಜುಗಳನ್ನು ಪರಿಶೀಲಿಸಿ, ಸಮಾಜ ಕಲ್ಯಾಣ ಯೋಜನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ ಮತ್ತು ಯಾವುದೇ ದಲ್ಲಾಳಿಗಳಿಲ್ಲದೆ ಸುಲಭವಾದ ಭಾಷೆಯಲ್ಲಿ ಸರಕಾರಿ ಪ್ರಕ್ರಿಯೆಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.",
    search_placeholder: "ಹುಡುಕಿ 'ಆಧಾರ್ ತಿದ್ದುಪಡಿ', 'ಚಾಲನಾ ಪರವಾನಗಿ', 'ಆಯುಷ್ಮಾನ್ ಆರೋಗ್ಯ ಕಾರ್ಡ್'...",
    search_btn: "ಹುಡುಕು",
    nav_services: "ಸೇವೆಗಳು",
    nav_documents: "ದಾಖಲೆ ಪರಿಶೀಲಕ",
    nav_schemes: "ಯೋಜನೆ ಹುಡುಕಕ",
    nav_track: "ಅರ್ಜಿ ಟ್ರ್ಯಾಕಿಂಗ್",
    nav_my_apps: "ನನ್ನ ಸೇವಾ ಕೇಂದ್ರ",
    stats_services: "12+ ಸಕ್ರಿಯ ಸೇವೆಗಳು",
    stats_languages: "8+ ಭಾರತೀಯ ಭಾಷೆಗಳು",
    stats_middlemen: "0% ಮಧ್ಯವರ್ತಿ ಶುಲ್ಕ",
    stats_free: "ಉಚಿತ ಪರಿಶೀಲನೆ",
    stats_label_1: "ವಿವರವಾದ ಕೇಂದ್ರ ಹಾಗೂ ರಾಜ್ಯ ಸೇವೆಗಳು",
    stats_label_2: "ಓದಿ, ಭಾಷಾಂತರಿಸಿ ಹಾಗೂ ನಿಮ್ಮ ಸ್ವಂತ ಧ್ವನಿಯಲ್ಲಿ ಕೇಳಿ",
    stats_label_3: "ನೇರವಾಗಿ ಅಧಿಕೃತ ಲಿಂಕ್‌ಗಳು ಮತ್ತು ಮಾರ್ಗಸೂಚಿಗಳು",
    stats_label_4: "ತ್ವರಿತ ಪರಿಶೀಲನೆ ನಿಯಮಗಳ ಚೆಕ್‌ಲಿಸ್ಟ್",
    section_categories: "ಕ್ಷೇತ್ರವಾರು ಅನ್ವೇಷಿಸಿ",
    section_popular: "ಜನಪ್ರಿಯ ನಾಗರಿಕ ಸೇವೆಗಳು",
    section_how_it_works: "ಸರ್ಕಾರಿ ಪ್ರಕ್ರಿಯೆ ಹೇಗೆ ಸುಲಭವಾಗುತ್ತದೆ",
    step1_title: "1. ತಕ್ಷಣವೇ ಹುಡುಕಿ",
    step1_desc: "ಬುದ್ಧಿವಂತ ಬಹುಭಾಷಾ ಸ್ವಯಂ-ಸಲಹೆಗಳೊಂದಿಗೆ ಯಾವುದೇ ಕೇಂದ್ರ ಅಥವಾ ರಾಜ್ಯ ಸೇವೆಗಳನ್ನು ಹುಡುಕಿ.",
    step2_title: "2. ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ",
    step2_desc: "ಅರ್ಜಿ ಅನುಮೋದನೆಗೆ ಅಗತ್ಯವಿರುವ ಕಾನೂನು ದಾಖಲೆಗಳ ಕ್ರಿಯಾಶೀಲ ಚೆಕ್‌ಲಿಸ್ಟ್ ರಚಿಸಿ.",
    step3_title: "3. ಅರ್ಹತೆಗಳನ್ನು ತಾಳೆನೋಡಿ",
    step3_desc: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ ಆಧಾರದ ಮೇಲೆ ಸೂಕ್ತವಾದ ಕಲ್ಯಾಣ ಯೋಜನೆಗಳು ಮತ್ತು ಸಬ್ಸಿಡಿಗಳನ್ನು ಮೌಲ್ಯಮಾಪನ ಮಾಡಿ.",
    step4_title: "4. ಸುರಕ್ಷಿತವಾಗಿ ಅರ್ಜಿ ಹಾಕಿ",
    step4_desc: "ಯಾವುದೇ ಕಮಿಷನ್ ಇಲ್ಲದೆ ನೇರವಾಗಿ ಅಧಿಕೃತ ಇಲಾಖಾ ಪೋರ್ಟಲ್‌ಗಳಿಗೆ ಮರುನಿರ್ದೇಶನ ಪಡೆಯಿರಿ.",
    chat_placeholder: "SevAI ಹತ್ತಿರ ನಿಮ್ಮ ನಾಗರಿಕ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ...",
    chat_welcome: "ನಮಸ್ಕಾರ! ನಾನು SevAI, ನಿಮ್ಮ ಡಿಜಿಟಲ್ ಇ-ಆಡಳಿತ ಸಲಹೆಗಾರ. ಅಗತ್ಯವಿರುವ ದಾಖಲೆಗಳು, ಸಮಾಜ ಕಲ್ಯಾಣ ಯೋಜನೆಗಳು ಮತ್ತು ಅರ್ಜಿ ಸಲ್ಲಿಸುವ ಪ್ರಕ್ರಿಯೆಗಳನ್ನು ಸುಲಭವಾದ ಮಾತುಗಳಲ್ಲಿ ಪರಿಶೀಲಿಸಲು ನಾಗರಿಕರಿಗೆ ಸಹಾಯ ಮಾಡುತ್ತೇನೆ. ಏನು ಬೇಕಾದರೂ ಕೇಳಿ!",
    footer_tagline: "SarkarSeva — ಪಾರದರ್ಶಕ ಡಿಜಿಟಲ್ ಆಡಳಿತದ ಮೂಲಕ ಭಾರತೀಯ ನಾಗರಿಕರನ್ನು ಸಬಲೀಕರಣಗೊಳಿಸುವುದು.",
    footer_disclaimer: "ಹಕ್ಕುತ್ಯಾಗ: ಈ ಡಿಜಿಟಲ್ ಪೋರ್ಟಲ್ ಕೇವಲ ಸುಲಭಗೊಳಿಸಿದ ಶೈಕ್ಷಣಿಕ ಮಾಹಿತಿ ಪ್ರದಾಯಕವಾಗಿದೆ. ನಾವು ಸರ್ಕಾರಿ ಸಂಸ್ಥೆಯಲ್ಲ. ಎಲ್ಲಾ ಲಿಂಕ್‌ಗಳು ಅಧಿಕೃತ ಪೋರ್ಟಲ್‌ಗಳಿಗೆ ಸುರಕ್ಷಿತವಾಗಿ ಮರುನಿರ್ದೇಶಿಸುತ್ತವೆ.",
    btn_apply: "ಅಧಿಕೃತ ಪೋರ್ಟಲ್‌ಗೆ ಹೋಗಿ",
    btn_download: "ಚೆಕ್‌ಲಿಸ್ಟ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    btn_track: "ಲೈವ್ ಸ್ಟೇಟಸ್ ವೀಕ್ಷಿಸಿ",
    btn_share: "ಗೈಡ್ ಹಂಚಿಕೊಳ್ಳಿ",
    badge_popular: "ಜನಪ್ರಿಯ",
    badge_new: "ಹೊಸತು",
    badge_scheme: "ಯೋಜನೆ",
    badge_free: "ಉಚಿತ",
    badge_online: "ಆನ್‌ಲೈನ್",
    badge_offline: "ಕೇಂದ್ರದಲ್ಲಿ"
  }
};

import { NEW_SERVICES } from './services_data';

export const SERVICES: ServiceDetails[] = NEW_SERVICES;

export const SCHEMES: Scheme[] = [
  {
    id: 'pm-awas-yojana',
    name: 'PM Awas Yojana (Urban)',
    description: 'Housing subsidy scheme helping Economically Weaker, Low Income, and Middle Income Group families acquire their first permanent brick home with a substantial interest subsidy on mortgages.',
    category: 'housing',
    matchPercentage: 95,
    eligibilityDescription: 'Annual household income matches classifications <= ₹18,00,000. Must not own any permanent concrete house anywhere in India. Min age 18.',
    genderCriteria: 'all',
    minAge: 18,
    maxAge: 85,
    incomeLimit: 1800000,
    occupationCriteria: ['Salaried Employee', 'Self-Employed', 'Business Owner', 'Unemployed'],
    benefits: ['Interest subsidy up to ₹2.67 Lakhs on housing loans', 'Mandatory co-ownership with female head of family', 'Preference for women, senior citizens and specially-abled individuals']
  },
  {
    id: 'pm-kisan',
    name: 'PM Kisan Samman Nidhi',
    description: 'An flagship initiative by the government of India providing solid financial income support to cultivable landholding farmer families across the nation.',
    category: 'agriculture',
    matchPercentage: 92,
    eligibilityDescription: 'Small and marginal landholder families occupying small cultivable spaces in native villages. Subject to institutional farm exceptions.',
    minAge: 18,
    maxAge: 110,
    occupationCriteria: ['Farmer'],
    benefits: ['₹6,000 cash credit annually delivered in three equal ₹2,000 cycles', 'Instant DBT ledger link, zero intermediaries', 'Access to crop insurance PM Fasal Bima subsidies']
  },
  {
    id: 'ayushman-bharat-pmy',
    name: 'Ayushman Bharat Yojana (PM-JAY)',
    description: 'National public health insurance scheme providing completely cashless medical coverage across top-tier empanelled community, public and private specialty hospitals.',
    category: 'health',
    matchPercentage: 90,
    eligibilityDescription: 'Individuals categorized under SECC socio-economic registry database or dynamic state ration programs. No family size cap.',
    minAge: 1,
    maxAge: 120,
    benefits: ['Cashless hospitalization cover up to ₹5,00,000 per family annually', 'All pre-existing medical conditions covered from Day 1', 'Covers diagnostic procedures, critical medications, and post-discharge recovery care']
  },
  {
    id: 'matru-vandana',
    name: 'Pradhan Mantri Matru Vandana Yojana',
    description: 'A direct maternity benefit cash incentive scheme encouraging optimal maternal nourishment, safe delivery practices and pediatric vaccination periods among women.',
    category: 'social',
    matchPercentage: 88,
    eligibilityDescription: 'Pregnant or lactating mothers, above 19 years of age, whose family income is moderate or falls below tax threshold.',
    genderCriteria: 'female',
    minAge: 19,
    maxAge: 50,
    benefits: ['₹5,000 cash incentive paid directly in installments', 'Mandatory check-ups counseling benefits', 'Pediatric immunizations credit records']
  },
  {
    id: 'samman-savings',
    name: 'Mahila Samman Savings Certificate',
    description: 'A dedicated, highly attractive micro-savings scheme launched by the Finance Ministry specifically for women and girl children offering high fixed interest rates.',
    category: 'education',
    matchPercentage: 85,
    eligibilityDescription: 'Any girl child or adult woman citizen, no specific income bar. Interest rate is 7.5% per annum.',
    genderCriteria: 'female',
    minAge: 1,
    maxAge: 110,
    benefits: ['Attractive 7.5% per annum fixed interest rate', 'Flexible deposit options up to ₹2 Lakhs', 'Partial withdrawal flexibility after one year']
  },
  {
    id: 'pm-svanidhi-scheme',
    name: 'PM SVANidhi Micro Credit Scheme',
    description: 'Special working capital micro-credit scheme seeking to empower street vendors, hawkers and basic trade artisans with collateral-free operating micro-loans.',
    category: 'business',
    matchPercentage: 87,
    eligibilityDescription: 'Active street vendors and municipal hawkers in urban, peri-urban, or adjoining rural regions.',
    minAge: 18,
    maxAge: 80,
    occupationCriteria: ['Street Vendor', 'Self-Employed'],
    benefits: ['Collateral-free working capital loan starting at ₹10,000', '7% interest subsidy on prompt monthly repayments', 'Immediate credit score upgrades for higher subsequent loans']
  },
  {
    id: 'post-matric-scholarship',
    name: 'Post-Matric Scholarship Scheme',
    description: 'Financial academic fee reimbursement program assisting backward category students (SC/ST/OBC) pursuing undergraduate, diploma or post-graduate college studies.',
    category: 'education',
    matchPercentage: 94,
    eligibilityDescription: 'Students enrolled in authorized college or technical institutions. Total annual parental household income under ₹2.5 Lakhs.',
    minAge: 15,
    maxAge: 35,
    incomeLimit: 250000,
    occupationCriteria: ['Student'],
    benefits: ['100% college tuition fee reimbursement directly to institution', 'Monthly maintenance allowance up to ₹1,200', 'Compulsory book bank access credit allowance']
  },
  {
    id: 'jan-dhan-yojana',
    name: 'Pradhan Mantri Jan Dhan Yojana (PMJDY)',
    description: 'National mission for financial inclusion ensuring poor and unbanked families acquire direct basic savings bank accounts with zero-balance requirements.',
    category: 'social',
    matchPercentage: 89,
    eligibilityDescription: 'All Indian citizens, specifically targeting low-income groups matching direct social benefits routing.',
    minAge: 10,
    maxAge: 120,
    benefits: ['No minimum balance requirement (Zero Balance Savings Account)', 'Free RuPay Debit Card with inbuilt ₹2,000,000 accident cover', 'Inbuilt ₹10,000 overdraft facility for eligible home managers']
  },
  {
    id: 'ujjwala-yojana',
    name: 'PM Ujjwala Yojana (LPG Support)',
    description: 'Clean energy transition scheme supplying free subsidized LPG cooking gas connections with auxiliary stovetop bundles to women from below-poverty households.',
    category: 'social',
    matchPercentage: 84,
    eligibilityDescription: 'Adult women belonging to BPL families, forest dwellers, or registered schedule category groups.',
    genderCriteria: 'female',
    minAge: 18,
    maxAge: 90,
    incomeLimit: 150000,
    benefits: ['Free structural installation of active LPG gas cylinder connection', 'Subsidy of ₹300 per cylinder cylinder refill', 'Free double-burner hotplate stovetop bundle']
  },
  {
    id: 'kaushal-vikas',
    name: 'PM Kaushal Vikas Yojana (PMKVY)',
    description: 'Skill certification scheme seeking to enable a large number of Indian youth to take up industry-relevant skill training for better livelihoods.',
    category: 'education',
    matchPercentage: 86,
    eligibilityDescription: 'School/college dropouts or unemployed native youth matching skilling credentials.',
    minAge: 15,
    maxAge: 45,
    occupationCriteria: ['Student', 'Unemployed'],
    benefits: ['Free government certified vocational skill training aligned with NSDC standards', 'Certified skill assess card increasing recruitment eligibility', 'INR 8,000 post-assessment stipend credits']
  },
  {
    id: 'mudra-loans',
    name: 'PM Mudra Yojana (PMMY)',
    description: 'Collateral-free commercial micro-loans mapping up to ₹10 Lakhs to non-corporate, non-farm small and micro entrepreneurs to scale active workshops.',
    category: 'business',
    matchPercentage: 91,
    eligibilityDescription: 'Micro entrepreneurs, small shopkeepers, artisans, or cottage workshop ventures. Ages 18 up to 75.',
    minAge: 18,
    maxAge: 75,
    occupationCriteria: ['Business Owner', 'Self-Employed'],
    benefits: ['Collateral-free commercial loan up to ₹10 Lakhs classified under Shishu, Kishor or Tarun tiers', 'Reasonable interest rates matching direct state financial margins', 'No processing fee charges on immediate micro-advances']
  },
  {
    id: 'social-pension',
    name: 'National Social Assistance Programme (NSAP)',
    description: 'Social pension support providing direct financial relief to senior citizens, widows, and specially-abled individuals belonging to lower-income segments.',
    category: 'social',
    matchPercentage: 93,
    eligibilityDescription: 'Elderly citizens, widows, or differently-abled individuals with household income strictly below state definition of poverty.',
    minAge: 60,
    maxAge: 120,
    incomeLimit: 120000,
    benefits: ['Monthly social pension credits directly seeded to accounts', 'Exempt from sudden asset evaluation checks once authorized', 'Joint medical welfare priorities at local district clinics']
  },
  {
    id: 'atal-pension',
    name: 'Atal Pension Yojana (APY)',
    description: 'Flagship co-contributory voluntary pension system structured specifically for workers in the unorganized labor sectors to preserve financial post-retirement age.',
    category: 'social',
    matchPercentage: 82,
    eligibilityDescription: 'Unorganized workers, farmers, delivery staff, or local labor citizens. Age range strictly between 18 to 40.',
    minAge: 18,
    maxAge: 40,
    occupationCriteria: ['Farmer', 'Street Vendor', 'Self-Employed', 'Unemployed'],
    benefits: ['Guaranteed financial pension of ₹1,000 to ₹5,000 monthly upon reaching 60 years old', 'Central government match contribution schemes', 'Complete spouse legal entitlement of pension assets on death of investor']
  },
  {
    id: 'beti-bachao',
    name: 'Beti Bachao Beti Padhao Scholarship',
    description: 'Comprehensive educational support scholarship and safe custody savings accounts launched to encourage high female school enrollments and health index indicators.',
    category: 'education',
    matchPercentage: 85,
    eligibilityDescription: 'Parents or girl children under Indian school enrollment, specifically targeting low-income families.',
    genderCriteria: 'female',
    minAge: 1,
    maxAge: 18,
    benefits: ['Special educational cash grants and scholarship covers', 'Priority access to high secondary school enrollments', 'Subsidized small savings bank options mapped for higher studies']
  },
  {
    id: 'pranam-scheme',
    name: 'PM-PRANAM (Fertilizer Support)',
    description: 'Agriculture support and state subsidy system promoting balanced commercial usage of chemical fertilizers combined with organic or bio-fertilizer formulations.',
    category: 'agriculture',
    matchPercentage: 83,
    eligibilityDescription: 'Registered farmers holding active crop logs, coordinating with cooperative fertilizer distribution shops.',
    minAge: 18,
    maxAge: 110,
    occupationCriteria: ['Farmer'],
    benefits: ['Access to deeply subsidized green chemical & organic fertilizers', 'Free Soil Health Cards with specialized district recommendations', 'Higher agriculture production yields through balanced soil treatments']
  }
];
